"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
APPS_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rg(j=r4br+!f!43dn2s(w_(np700%1nx#pw(aq+(^7t@@sj&#9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'import_export',
    'apps',
    'apps.authentication',
    'apps.home',
    'apps.inventory',
    'apps.shared',
    'apps.categorias',
    'apps.marcas',
    'apps.fornecedor',
    'apps.ativos',
    'apps.auditoria',
    'apps.tickets',
    'apps.produtos',
    'apps.movimentacao',
    'apps.notificacao',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

# Assets Management
ASSETS_ROOT = os.getenv('ASSETS_ROOT', '/static/assets')

TEMPLATE_DIR = os.path.join(APPS_DIR, "apps/templates")  # ROOT dir for templates
STATIC_DIR = os.path.join(APPS_DIR, "apps/static")  # ROOT dir for Static


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR, STATIC_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

AUTH_USER_MODEL = 'authentication.User'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema'
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Gestão de TI',
    'DESCRIPTION': 'Sem Descrição',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = 'media/'


LOGIN_URL = reverse_lazy('authentication:login')  # Página de login
LOGIN_REDIRECT_URL = reverse_lazy('home:dashboard')       # Redireciona para a homepage após login
LOGOUT_REDIRECT_URL = reverse_lazy('authentication:login')  # Redireciona para login após logout

# Configuração para recebimento de tickets por e-mail
TICKET_EMAIL_CONFIG = {
    # Servidor IMAP
    'IMAP_SERVER': 'imap.gmail.com',  # Gmail
    # 'IMAP_SERVER': 'outlook.office365.com',  # Outlook
    # 'IMAP_SERVER': 'imap.mail.yahoo.com',  # Yahoo
    'IMAP_PORT': 993,

    # Credenciais
    'EMAIL_USER': 'suporte@suaempresa.com',
    'EMAIL_PASSWORD': 'sua_senha_ou_app_password',

    # Configurações de processamento
    'AUTO_CREATE_USERS': True,  # Criar usuários automaticamente
    'PROCESS_ATTACHMENTS': True,  # Processar anexos
    'DEFAULT_CLIENTE_ID': 1,  # ID do cliente padrão (opcional)

    # NOTIFICAÇÕES
    'SEND_CONFIRMATION': True,  # Enviar confirmação ao criar ticket
    'NOTIFY_AGENT_ON_REPLY': True,  # Notificar técnico quando cliente responde
    'NOTIFY_CLIENT_ON_REPLY': True,  # Notificar cliente quando técnico responde

    # URL DO SISTEMA
    'SITE_URL': 'https://suporte.empresa.com',  # URL base para links
}

# E-mail de saída (para enviar notificações)
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'suporte@empresa.com'
EMAIL_HOST_PASSWORD = 'senha_ou_app_password'
DEFAULT_FROM_EMAIL = 'Suporte <suporte@empresa.com>'



# CELERY_BEAT_SCHEDULE = {
#     'check-machines-status': {
#         'task': 'apps.inventory.tasks.check_machines_status',
#         'schedule': 300.0,  # A cada 5 minutos
#     },
# }